### ISSUE TITLE
String interpolation support

### ISSUE THREAD

**Issue by foobit** [ThakeeNathees/miniscript#171]
Feature request: Add [String Interpolation](https://en.wikipedia.org/wiki/String_interpolation) support

E.g. something like this (C# style)
```
apples = 4
print($"I have {apples} apples.")
```

**Comment by ThakeeNathees** [comment]
Hi @foobit, I've marked it's on my todo list, which will be implemented sooner,  (I've commented some interpolation tokens on the source code which is below).
https://github.com/ThakeeNathees/pocketlang/blob/f3b220106c0665870f17e40b696eac65e14bf15b/src/pk_compiler.c#L145-L150
