### ISSUE TITLE
function redefinition

### ISSUE THREAD

**Issue by velkyel** [ThakeeNathees/miniscript#191]
Hello.
Pocketlang looks really nice.  I'd like to have function redefinition possibility.  then it's more REPL-like usage possible.

**Comment by ThakeeNathees** [comment]
I've been working on moving classes and functions to the constant buffer of a module and assigning them to global variables with their name, for the last couple of days.

As a result, it's possible to override the functions and classes, which is implemented at **[this]( https://github.com/ThakeeNathees/pocketlang/tree/fn-cls-moved-constants)** branch and will be merged soon.
